[package]
name = "ftr_parser"
version = "0.1.0"
edition = "2021"
license = "EUPL-1.2"

[dependencies]
lz4_flex = "0.11.2"
eyre = "0.6.12"
serde = { version = "1.0.197", features = ["derive"] }
num-bigint = { version = "0.4.4", features = ["serde"] }
half = "2.4.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

