[package]
name = "parser_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
lz4_flex = "0.11.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

